
PRAGMA foreign_keys = ON;
PRAGMA journal_mode = WAL;

CREATE TABLE Chunks(
  Id INTEGER PRIMARY KEY NOT NULL,
  Data BLOB NOT NULL
);

CREATE TABLE KeySets(
  Id TEXT UNIQUE PRIMARY KEY NOT NULL,
  Name TEXT NOT NULL
);

CREATE TABLE KeyGroups(
  Id TEXT UNIQUE PRIMARY KEY NOT NULL,
  Name TEXT NOT NULL
);

CREATE TABLE Keys(
  Id TEXT UNIQUE PRIMARY KEY NOT NULL,
  KeySetId TEXT NOT NULL REFERENCES KeySets(Id),
  KeyGroupId TEXT NOT NULL REFERENCES KeyGroups(Id),
  Name TEXT NOT NULL,
  FileName TEXT NULL,
  IsEncrypt BOOLEAN NOT NULL,
  IsArchive BOOLEAN NOT NULL,
  IsRevoked BOOLEAN NOT NULL,
  IsErasable BOOLEAN NOT NULL,
  TotalBytes INTEGER NOT NULL,
  ChunkSize INTEGER NOT NULL
);

CREATE TABLE KeyChunks(
  Id INTEGER PRIMARY KEY NOT NULL,
  KeyId TEXT NOT NULL REFERENCES Keys(Id),
  ChunkId INTEGER NOT NULL REFERENCES Chunks(Id)
);

CREATE TABLE KeyOffsets(
  KeyId TEXT UNIQUE PRIMARY KEY NOT NULL REFERENCES Keys(Id),
  ChunkId INTEGER NOT NULL REFERENCES Chunks(Id),
  Offset INTEGER NOT NULL,
  UsedBytes INTEGER NOT NULL
);

CREATE TABLE KeyProperties(
  Id INTEGER PRIMARY KEY NOT NULL,
  KeyId TEXT NOT NULL REFERENCES Keys(Id),
  Type TEXT NULL,
  Name TEXT NOT NULL,
  Value TEXT NULL
);

-- CREATE INDEX Keys_i1 ON Keys(KeySetId);
-- CREATE INDEX Keys_i2 ON Keys(KeyGroupId);
-- CREATE INDEX Keys_i3 ON Keys(Name);
-- CREATE INDEX Keys_i4 ON Keys(FileName);

CREATE UNIQUE INDEX KeyOffsets_i1 ON KeyOffsets(KeyId);
CREATE UNIQUE INDEX KeyChunks_i1 ON KeyChunks(KeyId, ChunkId);
CREATE UNIQUE INDEX KeyProperties_i1 ON KeyProperties(KeyId, Name);
